default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5435) %>
  username: <%= ENV.fetch("DB_USER", "chamados") %>
  password: <%= ENV.fetch("DB_PASSWORD", "chamados") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: chamados_development

test:
  <<: *default
  database: chamados_test

production:
  <<: *default
  database: chamados_production
